=== grimace87/ShiningEngine/scenegen/resources/scene.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Application scene generation",
  "description": "Description of rendering requirements for a scene in an application",
  "required": [
    "id",
    "camera",
    "resources",
    "passes"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "camera": {
      "type": "string",
      "enum": [
        "player",
        "flight_path"
      ]
    },
    "resources": {
      "type": "object",
      "required": [
        "models",
        "textures",
        "fonts"
      ],
      "properties": {
        "models": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "id"
            ],
            "id": {
              "type": "string"
            },
            "file": {
              "type": "string"
            },
            "generator": {
              "type": "string",
              "enum": [
                "skybox",
                "text"
              ]
            }
          }
        },
        "textures": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "type": "string"
              },
              "format": {
                "type": "string",
                "enum": [
                  "r8",
                  "rgb8",
                  "rgba8",
                  "d16"
                ]
              },
              "file": {
                "type": "string"
              },
              "kind": {
                "type": "string",
                "enum": [
                  "cubemap",
                  "uninitialised"
                ]
              }
            }
          }
        },
        "fonts": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "id",
              "file",
              "texture_id"
            ],
            "properties": {
              "id": {
                "type": "string"
              },
              "file": {
                "type": "string"
              },
              "texture_id": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "passes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "kind",
          "steps"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "kind": {
            "type": "string",
            "enum": [
              "default",
              "offscreen"
            ]
          },
          "target_texture_ids": {
            "type": "object",
            "required": [
              "colour_texture_id"
            ],
            "properties": {
              "colour_texture_id": {
                "type": "string"
              },
              "depth_texture_id": {
                "type": "string"
              }
            }
          },
          "steps": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "name",
                "render",
                "model_id",
                "texture_ids"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "render": {
                  "type": "string",
                  "enum": [
                    "basic_textured",
                    "text_paint",
                    "reflection_pre_render"
                  ]
                },
                "model_id": {
                  "type": "string"
                },
                "texture_ids": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== grimace87/ShiningEngine/scenegen/resources/test/deserialiser/full_featured_app/scene.json
{
  "id": "scene",
  "camera": "player",
  "resources": {
    "models": [
      {
        "id": "terrain",
        "file": "SceneTerrain.mdl"
      },
      {
        "id": "river",
        "file": "River.mdl"
      }
    ],
    "textures": [
      {
        "id": "outdoors",
        "format": "rgba8",
        "file": "simple_outdoor_texture.jpg"
      },
      {
        "id": "reflection_colour",
        "format": "rgb8",
        "kind": "uninitialised"
      },
      {
        "id": "reflection_depth",
        "format": "d16",
        "kind": "uninitialised"
      }
    ],
    "fonts": []
  },
  "passes": [
    {
      "name": "pre_reflection",
      "kind": "offscreen",
      "target_texture_ids": {
        "colour_texture_id": "reflection_colour",
        "depth_texture_id": "reflection_depth"
      },
      "steps": [
        {
          "name": "skybox",
          "render": "reflection_pre_render",
          "model_id": "skybox",
          "texture_ids": ["skybox"]
        },
        {
          "name": "terrain",
          "render": "reflection_pre_render",
          "model_id": "terrain",
          "texture_ids": ["outdoors"]
        }
      ]
    },
    {
      "name": "compose",
      "kind": "default",
      "steps": [
        {
          "name": "skybox",
          "render": "basic_textured",
          "model_id": "skybox",
          "texture_ids": ["skybox"]
        },
        {
          "name": "river",
          "render": "basic_textured",
          "model_id": "river",
          "texture_ids": ["reflection"]
        },
        {
          "name": "terrain",
          "render": "basic_textured",
          "model_id": "terrain",
          "texture_ids": ["outdoors"]
        }
      ]
    },
    {
      "name": "hud",
      "kind": "default",
      "steps": [
        {
          "name": "text_overlay",
          "render": "text_paint",
          "model_id": "hud",
          "texture_ids": ["musica"]
        }
      ]
    }
  ]
}

=== grimace87/ShiningEngine/scenegen/resources/test/deserialiser/full_featured_app/cutscene.json
{
  "id": "cutscene",
  "camera": "flight_path",
  "resources": {
    "models": [
      {
        "id": "skybox",
        "generator": "skybox"
      }
    ],
    "textures": [
      {
        "id": "skybox",
        "format": "rgb8",
        "file": "bluecloud.jpg",
        "kind": "cubemap"
      }
    ],
    "fonts": []
  },
  "passes": [
    {
      "name": "skybox",
      "kind": "default",
      "steps": [
        {
          "name": "box",
          "render": "basic_textured",
          "model_id": "skybox",
          "texture_ids": ["skybox"]
        }
      ]
    }
  ]
}

=== grimace87/ShiningEngine/scenegen/resources/test/generator/full_featured_app/spec/cutscene.json
{
  "id": "cutscene",
  "camera": "player",
  "resources": {
    "models": [
      {
        "id": "skybox",
        "generator": "skybox"
      }
    ],
    "textures": [
      {
        "id": "skybox",
        "format": "rgba8",
        "file": "bluecloud.jpg",
        "kind": "cubemap"
      }
    ],
    "fonts": []
  },
  "passes": [
    {
      "name": "skybox",
      "kind": "default",
      "steps": [
        {
          "name": "box",
          "render": "basic_textured",
          "model_id": "skybox",
          "texture_ids": ["skybox"]
        }
      ]
    }
  ]
}
